---
title: CPF2909Exception class
description: "The exception that is thrown when Error clearing member {0} in file {1} in {2}. "
last_modified_at: 2024-06-28T18:18:37Z
---

The exception that is thrown when Error clearing member {0} in file {1} in {2}.

**Namespace:** ASNA.QSys.Runtime.JobSupport
**Assembly:** ASNA.QSys.Runtime.dll

**Inheritance:** [Object](https://docs.microsoft.com/en-us/dotnet/api/system.object) --> [Exception](https://docs.microsoft.com/en-us/dotnet/api/system.exception) --> [JobException](/reference/runtime/qsys-runtime-job-support/job-exception.html) --> [CPF0000Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf0000-exception.html) --> [CPF2900Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2900-exception.html)
<br>
<br>

## Constructors

| Name | Description |
| --- | --- |
| [CPF2909Exception](#cpf2909exceptionstring-string-string-exception)([String](https://docs.microsoft.com/en-us/dotnet/api/system.string), [String](https://docs.microsoft.com/en-us/dotnet/api/system.string), [String](https://docs.microsoft.com/en-us/dotnet/api/system.string), [Exception](https://docs.microsoft.com/en-us/dotnet/api/system.exception)) | Initializes a new instance of the CPF2909Exception class.

### CPF2909Exception([String](https://docs.microsoft.com/en-us/dotnet/api/system.string), [String](https://docs.microsoft.com/en-us/dotnet/api/system.string), [String](https://docs.microsoft.com/en-us/dotnet/api/system.string), [Exception](https://docs.microsoft.com/en-us/dotnet/api/system.exception))

Initializes a new instance of the CPF2909Exception class.

```cs
CPF2909Exception(String, String, String, Exception)
```

#### Parameters

| Type | Parameter name | Description
| --- | --- | ---
| [String](https://docs.microsoft.com/en-us/dotnet/api/system.string) | library | The name of the library.
| [String](https://docs.microsoft.com/en-us/dotnet/api/system.string) | file | The name of the file.
| [String](https://docs.microsoft.com/en-us/dotnet/api/system.string) | member | The name of the member.
| [Exception](https://docs.microsoft.com/en-us/dotnet/api/system.exception) | innerException | The exception that is the cause of the current exception, or a null reference if no inner exception is specified.
