---
title: CPFA094Exception class
description: The exception that is thrown when Path name not specified.
---

The exception that is thrown when Path name not specified.

**Namespace:** ASNA.QSys.Runtime.JobSupport
**Assembly:** ASNA.QSys.Runtime.dll

**Inheritance:** [Object](https://docs.microsoft.com/en-us/dotnet/api/system.object) --> [Exception](https://docs.microsoft.com/en-us/dotnet/api/system.exception) --> [JobException](/reference/runtime/qsys-runtime-job-support/job-exception.html) --> [CPF0000Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf0000-exception.html) --> [CPFA000Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpfa000-exception.html)
<br>
<br>

## Constructors

| Name | Description |
| --- | --- |
| [CPFA094Exception](#cpfa094exceptionexception)([Exception](https://docs.microsoft.com/en-us/dotnet/api/system.exception)) | Initializes a new instance of the CPFA094Exception class.

### CPFA094Exception([Exception](https://docs.microsoft.com/en-us/dotnet/api/system.exception))

Initializes a new instance of the CPFA094Exception class.

```cs
CPFA094Exception(Exception)
```

#### Parameters

| Type | Parameter name | Description
| --- | --- | ---
| [Exception](https://docs.microsoft.com/en-us/dotnet/api/system.exception) | innerException | The exception that is the cause of the current exception, or a null reference if no inner exception is specified.
