---
title: CPF Exceptions
description: TOC Landing page for CPF Exceptions
---


| Type | Description |
| --- | --- |
| [CPF0000Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf0000-exception.html) | Defines the core behavior of all the CPFxxxx exceptions. |
| [CPF0001Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf0001-exception.html) | The exception that is thrown when an Error found on {0} command.  See Inner Exception. |
| [CPF0500Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf0500-exception.html) | Defines the core behavior of CPF05xx exceptions. |
| [CPF0555Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf0555-exception.html) | The exception that is thrown when Date not in specified format or date not valid: {0} |
| [CPF1000Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf1000-exception.html) | Defines the core behavior of CPF10xx exceptions. |
| [CPF1028Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf1028-exception.html) | The exception that is thrown when {0} not valid for parameter SYSVAL. |
| [CPF1095Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf1095-exception.html) | The exception that is thrown when CL variable length not valid for parameter {0} |
| [CPF1300Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf1300-exception.html) | Defines the core behavior of CPF10xx exceptions. |
| [CPF1338Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf1338-exception.html) | The exception that is thrown when Errors occurred on while submitting a job.. |
| [CPF2100Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2100-exception.html) | Defines the core behavior of CPF21xx exceptions. |
| [CPF2103Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2103-exception.html) | The exception that is thrown when Duplicate Library List entry {0} |
| [CPF2105Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2105-exception.html) | The exception that is thrown when Object {1} in {0} type {2} not found. |
| [CPF2108Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2108-exception.html) | The exception that is thrown when Object {1} type {2} not added to library {0} |
| [CPF210DException](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf210d-exception.html) | The exception that is thrown when Library {0} in use. |
| [CPF210EException](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf210e-exception.html) | The exception that is thrown when Library {0} not available for reason code {1} |
| [CPF2110Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2110-exception.html) | The exception that is thrown when Library {0} not found. |
| [CPF2111Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2111-exception.html) | The exception that is thrown when Library {0} already exists. |
| [CPF2113Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2113-exception.html) | The exception that is thrown when Cannot allocate library {0} |
| [CPF2117Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2117-exception.html) | The exception that is thrown when {0} Objects of type {1} were deleted but {2} were not deleted. |
| [CPF2123Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2123-exception.html) | The exception that is thrown when Description for object {0} not changed. |
| [CPF2125Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2125-exception.html) | The exception that is thrown when No objects were deleted for object {0}. |
| [CPF2136Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2136-exception.html) | The exception that is thrown when Renaming library {0} failed. |
| [CPF2138Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2138-exception.html) | The exception that is thrown when Creation of library {0} not allowed. |
| [CPF2139Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2139-exception.html) | The exception that is thrown when Rename of library {0} failed. |
| [CPF2151Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2151-exception.html) | The exception that is thrown when Operation failed for {1} in {0} type{2} |
| [CPF2161Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2161-exception.html) | The exception that is thrown when Cannot delete some objects in library {0} |
| [CPF2164Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2164-exception.html) | The exception that is thrown when Rename of library {0} not complete. |
| [CPF2166Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2166-exception.html) | The exception that is thrown when Library name {0} not valid. |
| [CPF2167Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2167-exception.html) | The exception that is thrown when Library {0} on library list and cannot be deleted. |
| [CPF2168Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2168-exception.html) | The exception that is thrown when Library {0} not deleted. |
| [CPF2176Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2176-exception.html) | The exception that is thrown when Library {0} damaged. |
| [CPF2182Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2182-exception.html) | The exception that is thrown when Not authorized to library {0} |
| [CPF2189Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2189-exception.html) | The exception that is thrown when Not authorized to object {0} in {1} type {2} |
| [CPF2200Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2200-exception.html) | Defines the core behavior of CPF22xx exceptions. |
| [CPF2203Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2203-exception.html) | The exception that is thrown when User profile {0} not correct. |
| [CPF2207Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2207-exception.html) | The exception that is thrown when Not authorized to use object {0} type {1} |
| [CPF2400Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2400-exception.html) | Defines the core behavior of CPF24xx exceptions. |
| [CPF2472Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2472-exception.html) | The exception that is thrown when Invalid wait time specified: {0} |
| [CPF2600Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2600-exception.html) | Defines the core behavior of CPF26xx exceptions. |
| [CPF2691Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2691-exception.html) | The exception that is thrown when Rename of {0} type {1} did not complete. |
| [CPF2696Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2696-exception.html) | The exception that is thrown when Object {0} type {1} not renamed. |
| [CPF2800Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2800-exception.html) | Defines the core behavior of CPF28xx exceptions. |
| [CPF2802Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2802-exception.html) | The exception that is thrown when From-file {0} in {1} not found. |
| [CPF2817Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2817-exception.html) | The exception that is thrown when Copy command ended because of error. |
| [CPF2861Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2861-exception.html) | The exception that is thrown when To-file {0} in {1} not found or not created. |
| [CPF2874Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2874-exception.html) | The exception that is thrown when Both to-file and from-file are the same. To-file {0} in library {1} is the same as the from-file. |
| [CPF2877Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2877-exception.html) | The exception that is thrown when *LIBL not allowed on TOFILE parameter with CRTFILE(*YES). |
| [CPF2883Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2883-exception.html) | The exception that is thrown when Error creating file {0} in library {1}. |
| [CPF2900Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2900-exception.html) | Defines the core behavior of CPF29xx exceptions. |
| [CPF2909Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2909-exception.html) | The exception that is thrown when Error clearing member {0} in file {1} in {2}. |
| [CPF2952Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2952-exception.html) | The exception that is thrown when Error opening file {0} in library {1}. |
| [CPF2963Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2963-exception.html) | The exception that is thrown when NFMTOPT(*NOCHK) required to copy file. |
| [CPF2969Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2969-exception.html) | The exception that is thrown when FMTOPT(*MAP *DROP) or FMTOPT(*NOCHK) required. |
| [CPF2976Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf2976-exception.html) | The exception that is thrown when Number of errors greater than ERRLVL value. |
| [CPF3000Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3000-exception.html) | Defines the core behavior of CPF30xx exceptions. |
| [CPF3011Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3011-exception.html) | The exception that is thrown when TYPE not found for file {0} in library {1} |
| [CPF3012Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3012-exception.html) | The exception that is thrown when File {0} in library {1} not found. |
| [CPF3061Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3061-exception.html) | The exception that is thrown when Record format {0} not found for outfile {1}. |
| [CPF3067Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3067-exception.html) | The exception that is thrown when Error while opening file {0} in {1} |
| [CPF3068Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3068-exception.html) | The exception that is thrown when Error while writing to file {0} in {1} |
| [CPF3092Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3092-exception.html) | The exception that is thrown when FILEATR specified not valid for {0} file {1} |
| [CPF3100Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3100-exception.html) | Defines the core behavior of CPF31xx exceptions. |
| [CPF3144Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3144-exception.html) | The exception that is thrown when Member {0} not cleared or initialized. |
| [CPF3200Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3200-exception.html) | Defines the core behavior of CPF32xx exceptions. |
| [CPF3203Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3203-exception.html) | The exception that is thrown when Cannot allocate object for file {0} in {1}. |
| [CPF3204Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3204-exception.html) | The exception that is thrown when Cannot find object needed for file {0} in {1}. |
| [CPF320BException](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf320b-exception.html) | The exception that is thrown when Operation was not valid for database file {0}. |
| [CPF3220Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3220-exception.html) | The exception that is thrown when Cannot do operation on {0} in {1}. |
| [CPF323DException](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf323d-exception.html) | The exception that is thrown when User does not have correct authority. |
| [CPF3273Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3273-exception.html) | The exception that is thrown when File or member not created, deleted or changed. |
| [CPF3300Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3300-exception.html) | Defines the core behavior of CPF33xx exceptions. |
| [CPF3303Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3303-exception.html) | The exception that is thrown when File '{0}' not found in job '{1}/{2}/{3}' |
| [CPF3330Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3330-exception.html) | The exception that is thrown when Necessary resource not available {0} |
| [CPF3340Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3340-exception.html) | The exception that is thrown when *ONLY specified, but more than one file with specified name '{0}' found in job '{1}/{2}/{3}' |
| [CPF3357Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3357-exception.html) | The exception that is thrown when Output queue {0} does not exist. |
| [CPF3360Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3360-exception.html) | The exception that is thrown when Output queue {0} not deleted. Output queue in use. |
| [CPF338CException](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf338c-exception.html) | The exception that is thrown when Internal spool control file/folder '{0}' not accessible. |
| [CPF3400Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3400-exception.html) | Defines the core behavior of CPF34xx exceptions. |
| [CPF3429Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3429-exception.html) | The exception that is thrown when File {0} number {1} cannot be displayed, copied or sent. |
| [CPF3492Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf3492-exception.html) | The exception that is thrown when Not authorized to spooled file {0} |
| [CPF6700Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf6700-exception.html) | Defines the core behavior of CPF67xx exceptions. |
| [CPF6760Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf6760-exception.html) | The exception that is thrown when Device {0} not ready. |
| [CPF7000Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf7000-exception.html) | Defines the core behavior of CPF70xx exceptions. |
| [CPF7300Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf7300-exception.html) | Defines the core behavior of CPF73xx exceptions. |
| [CPF7302Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf7302-exception.html) | The exception that is thrown when File {0} not created in library {1} |
| [CPF7306Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf7306-exception.html) | The exception that is thrown when Member {0} not added to file {1} in {2} |
| [CPF7310Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf7310-exception.html) | The exception that is thrown when Member {0} not removed from file {1} in {2} |
| [CPF8800Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf8800-exception.html) | Defines the core behavior of CPF88xx exceptions. |
| [CPF88C4Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf88c4-exception.html) | The exception that is thrown when Value {0} for new object is not valid. |
| [CPF8A00Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf8a00-exception.html) | Defines the core behavior of CPF8Axx exceptions. |
| [CPF8A11Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf8a11-exception.html) | The exception that is thrown when An error occurred while checking document {0} in folder {1} |
| [CPF8A12Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf8a12-exception.html) | The exception that is thrown when Document {0} in folder {1} not copied. |
| [CPF8A13Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf8a13-exception.html) | The exception that is thrown when Document {0} in folder {1} not moved. |
| [CPF8A14Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf8a14-exception.html) | The exception that is thrown when {0} of type {1} not renamed to {2} in folder {3}. |
| [CPF8A16Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf8a16-exception.html) | The exception that is thrown when Document library objects not deleted. {0} objects deleted. |
| [CPF8A18Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf8a18-exception.html) | The exception that is thrown when Folder {0} not created. |
| [CPF8A77Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf8a77-exception.html) | The exception that is thrown when Folder {0} not found. |
| [CPF8A82Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf8a82-exception.html) | The exception that is thrown when Document {0} not found in folder {1} |
| [CPF8D00Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf8d00-exception.html) | Defines the core behavior of CPF8Dxx exceptions. |
| [CPF8D05Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf8d05-exception.html) | The exception that is thrown when Library {0} already exists. |
| [CPF9100Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf9100-exception.html) | Defines the core behavior of CPF91xx exceptions. |
| [CPF91CCException](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf91cc-exception.html) | The exception that is thrown when Command did not complete successfully. |
| [CPF9800Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf9800-exception.html) | Defines the core behavior of CPF98xx exceptions. |
| [CPF9801Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf9801-exception.html) | The exception that is thrown when Object {0} in library {1} not found. |
| [CPF9802Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf9802-exception.html) | The exception that is thrown when Not authorized to object {0} in {1} |
| [CPF9809Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf9809-exception.html) | The exception that is thrown when Library {0} cannot be accessed. |
| [CPF9810Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf9810-exception.html) | The exception that is thrown when Library {0} not found. |
| [CPF9812Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf9812-exception.html) | The exception that is thrown when Object {0} in library {1} not found. |
| [CPF9814Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf9814-exception.html) | The exception that is thrown when Device {0} not found. |
| [CPF9846Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf9846-exception.html) | The exception that is thrown when Error while processing file {0} in library {1} |
| [CPF9870Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf9870-exception.html) | The exception that is thrown when Object {0} type {2} already exists in library {1} |
| [CPF9899Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf9899-exception.html) | The exception that is thrown when Error occurred during processing of command. |
| [CPF9999Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpf9999-exception.html) | The exception that is thrown when a generic abnormal condition is found. |
| [CPFA000Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpfa000-exception.html) | Defines the core behavior of CPFA0xx exceptions. |
| [CPFA030Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpfa030-exception.html) | The exception that is thrown when Object {0} already in use. |
| [CPFA094Exception](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpfa094-exception.html) | The exception that is thrown when Path name not specified. |
| [CPFA0ABException](/reference/runtime/qsys-runtime-job-support/cpf-exceptions/cpfa0ab-exception.html) | The exception that is thrown when Operation failed for object. Object is {0} |
